---
title: Demo De SiteLeaf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title-bold: Forty
title-normal: by HTML5 UP
email: youremailaddress@gmail.com
description: 'Prueba de Jekyll + Siteleaf '
baseurl: 
url: 
author: 
street_address: 1234 Somewhere Road
city: Nashville
state: Asuncion
zip_code: 55555
country: Paraguay
phone: "(716) 555-5555"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji
tiles-source: posts
tiles-count: 6
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/andrewbanchich
markdown: kramdown
twitter:
  username: andrewbanchich
facebook:
  app_id: 
  publisher: 
  admins: 
logo: 
google_site_verification: 
